Repository PyTables/PyTables, pull requests merged in 2020-12, with the labels that each got.

#834 Add GitHub Actions for Tests
  .github/workflows/ci.yml
Labels: enhancement, in progress

#837 Out of order datatypes in Dataset #836
  tables/tableextension.pyx
  tables/tests/out_of_order_types.h5
  tables/tests/test_tables.py
Labels: enhancement

#843 Use integer division
  tables/hdf5extension.pyx
  tables/indexesextension.pyx
  tables/tableextension.pyx
  tables/utilsextension.pyx
Labels: enhancement

#846 A bunch of minor code quality refactorings
  bench/indexed_search.py
  bench/lookup_bench.py
  examples/array4.py
  examples/simple_threading.py
  examples/threading_monkeypatch.py
  tables/array.py
  tables/atom.py
  tables/attributeset.py
  tables/description.py
  tables/earray.py
  tables/expression.py
  tables/file.py
  tables/filters.py
  tables/flavor.py
  tables/group.py
  tables/hdf5extension.pyx
  tables/index.py
  tables/indexes.py
  tables/leaf.py
  tables/misc/proxydict.py
  tables/node.py
  tables/nodes/tests/test_filenode.py
  tables/scripts/pt2to3.py
  tables/table.py
  tables/tests/common.py
  tables/tests/test_array.py
  tables/tests/test_basics.py
  tables/tests/test_carray.py
  tables/tests/test_create.py
  tables/tests/test_earray.py
  tables/tests/test_enum.py
  tables/tests/test_queries.py
  tables/tests/test_tables.py
  tables/utils.py
  tables/vlarray.py
Labels: enhancement

#848 Declare support for Python 3.5–3.9 and remove older hacks
  .github/workflows/ci.yml
  README.rst
  examples/multiprocess_access_queues.py
  setup.py
  tables/tests/test_attributes.py
  tables/tests/test_basics.py
Labels: enhancement

#849 Doc code and typos
  doc/scripts/filenode.py
  doc/scripts/pickletrouble.py
  doc/scripts/tutorial1.py
  doc/source/FAQ.rst
  doc/source/MIGRATING_TO_2.x.rst
  doc/source/MIGRATING_TO_3.x.rst
  doc/source/conf.py
  doc/source/cookbook/hints_for_sql_users.rst
  doc/source/cookbook/no_root_install.rst
  doc/source/cookbook/py2exe_howto/pytables_test.py
  doc/source/other_material.rst
  doc/source/release-notes/RELEASE_NOTES_v0.8.rst
  doc/source/release-notes/RELEASE_NOTES_v0.9.rst
  doc/source/release-notes/RELEASE_NOTES_v1.0.rst
  doc/source/release-notes/RELEASE_NOTES_v2.0.x.rst
  doc/source/release-notes/RELEASE_NOTES_v2.1.x-pro.rst
  doc/source/release-notes/RELEASE_NOTES_v2.1.x.rst
  doc/source/release-notes/RELEASE_NOTES_v2.2.x-pro.rst
  doc/source/release-notes/RELEASE_NOTES_v2.2.x.rst
  doc/source/release-notes/RELEASE_NOTES_v2.4.x.rst
  doc/source/release-notes/RELEASE_NOTES_v3.0.x.rst
  doc/source/release-notes/RELEASE_NOTES_v3.2.x.rst
  doc/source/release-notes/RELEASE_NOTES_v3.5.x.rst
  doc/source/usersguide/index.rst
  doc/source/usersguide/installation.rst
  doc/source/usersguide/introduction.rst
  doc/source/usersguide/libref/link_classes.rst
  doc/source/usersguide/tutorials.rst
  doc/source/usersguide/usersguide.rst
Labels: documentation, website

#850 Drop Python 3.5 support, use f-strings and underscores in integers
  .github/workflows/ci.yml
  bench/chunkshape-bench.py
  bench/deep-tree-h5py.py
  bench/deep-tree.py
  bench/get-figures-ranges.py
  bench/get-figures.py
  bench/indexed_search.py
  bench/open_close-bench.py
  bench/poly.py
  bench/pytables_backend.py
  bench/search-bench-plot.py
  bench/split-file.py
  bench/table-copy.py
  doc/source/usersguide/installation.rst
  examples/earray1.py
  examples/links.py
  examples/multiprocess_access_queues.py
  examples/simple_threading.py
  examples/table1.py
  examples/threading_monkeypatch.py
  setup.py
  tables/atom.py
  tables/attributeset.py
  tables/description.py
  tables/exceptions.py
  tables/file.py
  tables/flavor.py
  tables/group.py
  tables/index.py
  tables/leaf.py
  tables/link.py
  tables/misc/enum.py
  tables/node.py
  tables/nodes/filenode.py
  tables/path.py
  tables/scripts/pt2to3.py
  tables/scripts/ptrepack.py
  tables/scripts/pttree.py
  tables/table.py
  tables/tests/check_leaks.py
  tables/tests/common.py
  tables/tests/test_indexes.py
  tables/tests/test_indexvalues.py
  tables/tests/test_queries.py
  tables/tests/test_timestamps.py
  tables/unimplemented.py
  tables/utils.py
  tables/vlarray.py
Labels: enhancement, in progress, python3
