Repository PyTables/PyTables, pull requests merged in 2024-08, with the labels that each got.

#1192 Fix numpy2 compat for test_indexvalues (Closes: #1185)
  tables/index.py
  tables/tests/test_indexvalues.py
Labels: defect

#1195 Feature/update requirememt files
  .github/workflows/requirements/build-requirements.txt
  .github/workflows/requirements/optional-requirements.txt
  .github/workflows/requirements/wheels-requirements.txt
  .github/workflows/wheels.yml
  Makefile
  pyproject.toml
  requirements.in
  requirements.txt
Labels: enhancement, CI, dependencies

#1201 MAINT: Lower verbosity in wheel build
  pyproject.toml
  tables/tests/test_all.py
Labels: defect, CI

#1205 FIX: Pass `refcheck=False` to `np.ndarray.resize()` for PyPy compat
  tables/tests/test_direct_chunk.py
Labels: defect

#1204 Fix dependency constraints (Closes #1200)
  pyproject.toml
Labels: defect, dependencies
